#!/usr/bin/env node
// Downloads pinned model files from models.lock.json, verifies SHA-256,
// and copies them into deterministic extension paths.
//
// Usage: node scripts/vendor-models.mjs
//
// Fails closed: missing files, hash mismatches, and unexpected redirects
// are all errors. Never downloads unpinned "main" at release time.

import { createHash } from "node:crypto";
import { createReadStream, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const LOCK_PATH = join(REPO_ROOT, "models.lock.json");
const MODELS_DIR = join(REPO_ROOT, "extension", "models");

async function main() {
  const lockRaw = await readFile(LOCK_PATH, "utf8");
  const lock = JSON.parse(lockRaw);

  for (const [modelId, spec] of Object.entries(lock)) {
    const destDir = join(MODELS_DIR, modelId);
    await mkdir(destDir, { recursive: true });

    for (const [filePath, fileSpec] of Object.entries(spec.files)) {
      const destPath = join(destDir, filePath);
      await mkdir(dirname(destPath), { recursive: true });

      // If already downloaded and hash matches, skip
      if (existsSync(destPath)) {
        const existingHash = await sha256(destPath);
        if (existingHash === fileSpec.sha256) {
          console.log(`  ✓ ${modelId}/${filePath} (cached)`);
          continue;
        }
      }

      const url = `${spec.repository}/resolve/${spec.revision}/${filePath}`;
      console.log(`  ↓ ${modelId}/${filePath} from ${url}`);

      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`Failed to download ${url}: ${response.status} ${response.statusText}`);
      }

      const buffer = Buffer.from(await response.arrayBuffer());
      const hash = createHash("sha256").update(buffer).digest("hex");

      if (hash !== fileSpec.sha256) {
        throw new Error(`SHA-256 mismatch for ${modelId}/${filePath}: expected ${fileSpec.sha256}, got ${hash}`);
      }

      await writeFile(destPath, buffer);
      console.log(`  ✓ ${modelId}/${filePath} verified`);
    }
  }

  // Generate provenance document
  await generateProvenance(lock);
  console.log("\nAll models vendored successfully.");
}

async function sha256(filePath) {
  return new Promise((resolve, reject) => {
    const hash = createHash("sha256");
    const stream = createReadStream(filePath);
    stream.on("data", (data) => hash.update(data));
    stream.on("end", () => resolve(hash.digest("hex")));
    stream.on("error", reject);
  });
}

async function generateProvenance(lock) {
  const lines = ["# Model Provenance", ""];
  lines.push("This document is auto-generated by `scripts/vendor-models.mjs`.");
  lines.push("Do not edit manually.");
  lines.push("");

  for (const [modelId, spec] of Object.entries(lock)) {
    lines.push(`## ${modelId}`);
    lines.push("");
    lines.push(`- **Repository:** ${spec.repository}`);
    lines.push(`- **Revision:** ${spec.revision}`);
    lines.push(`- **License:** ${spec.license || "See repository"}`);
    lines.push("");
    lines.push("| File | SHA-256 |");
    lines.push("|------|---------|");
    for (const [filePath, fileSpec] of Object.entries(spec.files)) {
      lines.push(`| \`${filePath}\` | \`${fileSpec.sha256}\` |`);
    }
    lines.push("");
  }

  const provenancePath = join(REPO_ROOT, "MODEL_PROVENANCE.md");
  await writeFile(provenancePath, lines.join("\n"), "utf8");
  console.log(`  ✓ Generated ${provenancePath}`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
